### ISSUE TITLE
"ant runtests" get stuck

### ISSUE THREAD

**Issue by erights** [google/caja#1997]
"ant runtests" consistently gets stuck in get-scan-min

guest-scan-min	Failure	800000 ms passed while waiting for: completion (Remaining elements = [<div id="testUniverse-caja-guest-0___" class="testcontainer">])

junit.framework.AssertionFailedError: 800000 ms passed while waiting for: completion (Remaining elements = [<div id="testUniverse-caja-guest-0___" class="testcontainer">])
	at com.google.caja.plugin.BrowserTestCase.countdown(BrowserTestCase.java:262)
	at com.google.caja.plugin.BrowserTestCase.waitForCompletion(BrowserTestCase.java:222)
	at com.google.caja.plugin.BrowserTestCase.driveBrowser(BrowserTestCase.java:209)
	at com.google.caja.plugin.BrowserTestCase.runBrowserTest(BrowserTestCase.java:130)
	at com.google.caja.plugin.CatalogTestCase.runTest(CatalogTestCase.java:34)
	at com.google.caja.plugin.CatalogRunner$1.evaluate(CatalogRunner.java:94)
	at com.google.caja.plugin.CatalogRunner.runChild(CatalogRunner.java:88)
	at com.google.caja.plugin.CatalogRunner.runChild(CatalogRunner.java:42)

**Comment by erights** [comment]
<img width="764" alt="screen shot 2016-02-19 at 6 18 11 pm" src="https://cloud.githubusercontent.com/assets/273868/13194078/410c5ed8-d73a-11e5-8fa0-a5397b5c4310.png">

**Comment by kpreid** [comment]
Thanks for filing this — it's another thing I've hit myself and forgot to write down. Though your screenshot shows a different place (related to iterators IIRC).

Do you confirm it does _not_ hang on Chrome (`ant brtest -Dtest.browser=chrome`)?

(By the way, to finish running other tests faster than the timeout, you can close the hung browser window.)

**Comment by erights** [comment]
> ant brtest -Dtest.browser=chrome

I confirm that it does not stuck. However, it does give two other errors where are unrelated to guest-scan-min. Attached.

[0_MainBrowserTest-err.txt](https://github.com/google/caja/files/139386/0_MainBrowserTest-err.txt)
![screen shot 2016-02-20 at 3 30 02 pm](https://cloud.githubusercontent.com/assets/273868/13199867/faa3c604-d7e6-11e5-91a7-f32eb5bd27d3.png)
![screen shot 2016-02-20 at 3 30 20 pm](https://cloud.githubusercontent.com/assets/273868/13199869/fdf0efee-d7e6-11e5-8272-b3ca90b64cb4.png)
![screen shot 2016-02-20 at 3 30 38 pm](https://cloud.githubusercontent.com/assets/273868/13199871/02cd9fb2-d7e7-11e5-9d0c-4b0b79f4dd65.png)

**Comment by kpreid** [comment]
The hang was fixed in commit f94c71cbc0640532ecd62e734fd7ea8ae7379df0.
